In [20]:
begin_num = 2000
end_num = 3201
for x in range(2000, 3201):
  if x % 7 ==0 and x % 5==0:
   print(x)



2030
2065
2100
2135
2170
2205
2240
2275
2310
2345
2380
2415
2450
2485
2520
2555
2590
2625
2660
2695
2730
2765
2800
2835
2870
2905
2940
2975
3010
3045
3080
3115
3150
3185


In [16]:
num = 1
i = 5
while i > 1:
    num *= i
    i -= 1
print(num)
    

120


In [53]:
n=6
my_dict={x:x**2 for x in range(6)} 
print(suite_carre)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [4]:
name = "hello"
print(name[1:5]) # ici on supprime la lettre H
print(name[0:3]) # ici on supprime les lettres L et O


ello
hel


In [10]:
import numpy as np
#calcule de matrice de covariance de deux tableaux donnés. 
array1= np.array ([0, 1, 2])
array2= np.array ([2, 1, 0])
print(array1)
print(array2)
print("[[ 1. -1.] [-1. 1.]]", np.cov([0, 1, 2],[2, 1, 0] ))

[0 1 2]
[2 1 0]
[[ 1. -1.] [-1. 1.]] [[ 1. -1.]
 [-1.  1.]]


In [4]:
import math
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print(','.join(value))

180
24
